In [1]:
from pathlib import Path
import pandas as pd
from hemmelig import data_path

p = Path(data_path)

filer = [e for e in p.iterdir() if "lanekassen" in e.name]

dfs = []
for e in filer:
    with e.open("rb") as f:
        dfs.append(pd.read_json(e, lines=True))


df = pd.concat(dfs)
df

,doc_hash,lang,url,domain,date,mimetype,fulltext
0,b5fc6f81d5709f0051da1964c3900e7ca8df65f7,nno,http://lanekassen.no/globalassets/brosjyrer-fe...,lanekassen.no,2022-12-19 01:53:28+00:00,pdf,[Er du flyktning? Du blir rekna som flyktning ...
1,1fbe096fdfdd9916be1313006ac5cf44ac650231,nno,http://lanekassen.no/globalassets/skjemaer-fel...,lanekassen.no,2022-12-19 01:57:14+00:00,pdf,"[, , Du kan bruke dette skjemaet dersom du tar..."
2,582aaf9a510b3bde21b5b3e13ffc3453d6ca8174,nno,http://lanekassen.no/globalassets/skjemaer-fel...,lanekassen.no,2022-12-19 01:57:21+00:00,pdf,"[, , Det er viktig at du les informasjonen på ..."
3,32e23cf05e4db850a9e2f622c2edd0482572677e,nno,http://lanekassen.no/globalassets/skjemaer-fel...,lanekassen.no,2022-12-19 02:00:45+00:00,pdf,[Nynorsk Skjema for lærlinglønn Kor stort bort...
4,4ea46648c7ce59fe0c39b45779ed6402d8b41369,nno,http://lanekassen.no/globalassets/skjemaer-fel...,lanekassen.no,2022-12-19 02:01:01+00:00,pdf,[Nynorsk Skjema I – artikkelnr. 9001550 – nyno...
...,...,...,...,...,...,...,...
72,e29a43da7165d92d937c56416d50f563201ab5fa,nob,http://lanekassen.no/siteassets/skjemaer-og-fi...,lanekassen.no,2022-12-19 02:50:18+00:00,pdf,"[, , 01.01.2020 Storebrand Bank ASA 70 % Bolig..."
73,c120ee7f582c758ae392b8f90795a7c664c39e90,nob,http://lanekassen.no/siteassets/skjemaer-og-fi...,lanekassen.no,2022-12-19 02:50:23+00:00,pdf,"[, , 06.11.2019 Storebrand Bank ASA 70 % Bolig..."
74,553101a9b0a9fac935cf31e5dd59555d23ecbefe,nob,https://statistikk.lanekassen.no/globalassets/...,lanekassen.no,2022-12-19 03:10:41+00:00,pdf,"[, , Flyktningstipendet Mottakere av flyktning..."
75,1f14c7bcc564613f79be7a8cae1a946e27cfd755,nob,https://statistikk.lanekassen.no/globalassets/...,lanekassen.no,2022-12-19 03:10:44+00:00,pdf,"[, , Tall og fakta om Lånekassens kunder og or..."
76,ad84c32284570d5883b5c12276961d0a74ec1649,nob,https://statistikk.lanekassen.no/globalassets/...,lanekassen.no,2022-12-19 03:10:46+00:00,pdf,[Bruk av studiestøtte blant studenter med innv...

In [2]:
nynorske = df[df.lang == "nno"]
nynorske.index = range(len(nynorske))

bokmålske = df[df.lang == "nob"]
bokmålske.index = range(len(bokmålske))

len(nynorske), len(bokmålske)

(256, 310)

# Filtrer på språkkode i url

In [3]:
nynorske_url = nynorske[nynorske.url.apply(lambda x: "nn-NO" in x)]
nynorske_url

,doc_hash,lang,url,domain,date,mimetype,fulltext
34,fb85b9a3092ded7a1d46bda9b84f04f4bed42848,nno,http://lanekassen.no/nn-NO/stipend-og-lan/nore...,lanekassen.no,2022-12-19 01:38:24+00:00,html,"[Universitet og høgskole, Hoyskole og universi..."
35,b02a050068863a934a07125f43fcbe02d65e83a7,nno,http://lanekassen.no/nn-NO/stipend-og-lan/nore...,lanekassen.no,2022-12-19 01:38:26+00:00,html,"[Kven har ikkje ungdomsrett?, Tek du opp igjen..."
36,5c216471f5f7ffe165523ca0da6c2e359a0cffd3,nno,http://lanekassen.no/nn-NO/stipend-og-lan/nore...,lanekassen.no,2022-12-19 01:38:30+00:00,html,"[Fagskole, Fagskole, Fagskoleutdanning, Du kan..."
37,2700f5fbc1dd6a5b08ff2e0ce167d62fd4d62bf1,nno,http://lanekassen.no/nn-NO/stipend-og-lan/nore...,lanekassen.no,2022-12-19 01:38:32+00:00,html,"[Lån og stipend for å gå på folkehøgskole, Er ..."
38,57dc5c0a45d9fd7b37276cf65330783e0a268d74,nno,http://lanekassen.no/nn-NO/stipend-og-lan/nore...,lanekassen.no,2022-12-19 01:38:35+00:00,html,"[Bibel- eller kunstskole, Elever på bibelskole..."
...,...,...,...,...,...,...,...
248,125a109bcfd9662f6ff605a402c7042ab0fec8ca,nno,https://larestedsinfo.lanekassen.no/nn-NO/nyhe...,lanekassen.no,2022-12-19 02:30:10+00:00,html,"[Ekstra betalingsutsettingar ut 2022, Alle som..."
249,3c805e96e675d03b75ea47e57b261247c4e1d61a,nno,https://larestedsinfo.lanekassen.no/nn-NO/nyhe...,lanekassen.no,2022-12-19 02:30:12+00:00,html,[Unntak for inntektsgrense for enkelte grupper...
250,6e3448b22b4de4c8147b86ec4d003a68c05a34f5,nno,https://larestedsinfo.lanekassen.no/nn-NO/nyhe...,lanekassen.no,2022-12-19 02:30:14+00:00,html,[Elevar kan få omgjort delar av tilleggslån ko...
251,656dda208d1438e3a12d14c31f01cd60cec5f6ed,nno,http://lanekassen.no/nn-NO/presse-og-samfunnsk...,lanekassen.no,2022-12-19 02:30:53+00:00,html,"[Saksgangen i klagesaker, Det er forvaltningsl..."
252,5f00fb68c536f6a7dbdff53366ecbf874109881f,nno,http://lanekassen.no/nn-NO/regelverk/endringsf...,lanekassen.no,2022-12-19 02:31:02+00:00,html,"[Merknad til § 2-4 - 20, Merknad, Når det blir..."

In [4]:
bokmålske_url = bokmålske[bokmålske.url.apply(lambda x: "nb-NO" in x)]
bokmålske_url

,doc_hash,lang,url,domain,date,mimetype,fulltext
0,6d87f8f74ffbd771311bf08814f8434f39101785,nob,http://lanekassen.no/nb-NO/stipend-og-lan/norg...,lanekassen.no,2022-12-19 01:35:46+00:00,html,"[Universitet og høgskole, Her finner du inform..."
1,a9ea2c0f4d93f69e29bc65a1242c293d0f97d808,nob,http://lanekassen.no/nb-NO/stipend-og-lan/norg...,lanekassen.no,2022-12-19 01:35:49+00:00,html,"[Hvem har ikke ungdomsrett?, Tar du opp fag, h..."
2,30b1784ef936658df1a41073b431686bef6c77a7,nob,http://lanekassen.no/nb-NO/stipend-og-lan/norg...,lanekassen.no,2022-12-19 01:35:53+00:00,html,"[Fagskole, Fagskole, Fagskoleutdanning, Du kan..."
3,d1def062d4065488a0ae9573bdfd7dbbea5fa5aa,nob,http://lanekassen.no/nb-NO/stipend-og-lan/norg...,lanekassen.no,2022-12-19 01:35:56+00:00,html,"[Lån og stipend for å gå på folkehøgskole, Er ..."
4,3942ec640adcb8392d1085643def74bb3f6806a7,nob,http://lanekassen.no/nb-NO/stipend-og-lan/norg...,lanekassen.no,2022-12-19 01:35:58+00:00,html,"[Bibel- eller kunstskole, Elever på bibelskole..."
...,...,...,...,...,...,...,...
221,aacb155a0fcc7887ca2d507a709a59bc8fff9e27,nob,https://larestedsinfo.lanekassen.no/nb-NO/nyhe...,lanekassen.no,2022-12-19 02:20:01+00:00,html,"[Ekstra betalingsutsettelser ut 2022, Alle som..."
222,1665d2bbe651b4090b9655dd4e06421578e039fc,nob,https://larestedsinfo.lanekassen.no/nb-NO/nyhe...,lanekassen.no,2022-12-19 02:20:06+00:00,html,[Elever kan få omgjort deler av tilleggslån ko...
223,8827548c3ccdce4feda50d5835be992043b9cf56,nob,https://larestedsinfo.lanekassen.no/nb-NO/nyhe...,lanekassen.no,2022-12-19 02:20:08+00:00,html,[Elever og studenter kan nå søke om lån og sti...
224,03305427fbd10a8aba257df55bd686fbcf749d5a,nob,https://larestedsinfo.lanekassen.no/nb-NO/nyhe...,lanekassen.no,2022-12-19 02:20:10+00:00,html,[Endringer i Lånekassens regler for studieåret...
225,a1823e2bd697ecde97c63280486b66252bd5ace5,nob,http://lanekassen.no/nb-NO/presse-og-samfunnsk...,lanekassen.no,2022-12-19 02:21:36+00:00,html,"[Saksgangen i klagesaker, Det er forvaltningsl..."

## Tekster med omvendt språkkode i url

In [5]:
nynorske[nynorske.url.apply(lambda x: "nb-NO" in x)]

,doc_hash,lang,url,domain,date,mimetype,fulltext
231,f79f1b8975fe57e0280509fa404b521f2522f3df,nno,http://lanekassen.no/nb-NO/regelverk/endringsf...,lanekassen.no,2022-12-19 02:22:39+00:00,html,"[Merknad, Merknad til § 2-4, Merknad, Når det ..."

In [6]:
bokmålske[bokmålske.url.apply(lambda x: "nn-NO" in x)]

,doc_hash,lang,url,domain,date,mimetype,fulltext
201,90f6946d71bc2631aadcee11c8c834bf95972849,nob,http://lanekassen.no/nn-NO/stipend-og-lan/nord...,lanekassen.no,2022-12-19 01:57:00+00:00,html,[Søknad om lån og stipend til gradsutdanning e...
202,d322c6c03ed84a6ff6ca404ab98bd02de3e9a85c,nob,http://lanekassen.no/nn-NO/stipend-og-lan/nore...,lanekassen.no,2022-12-19 01:58:57+00:00,html,"[Flyktningstipend, Flyktninger som ikke får in..."
203,78741013dda2ec205781f1ebc67b72d1840c9f08,nob,https://larestedsinfo.lanekassen.no/nn-NO/nyhe...,lanekassen.no,2022-12-19 02:00:29+00:00,html,[Endringer i Lånekassens forskrifter for studi...
204,47654c4f5bfcf29c6aef5b6a912277e274b52317,nob,http://lanekassen.no/nn-NO/presse-og-samfunnsk...,lanekassen.no,2022-12-19 02:03:16+00:00,html,[Ny liste over universitet som gir rett til ut...

# Finn par av urler der kun språkkoden er ulik

In [7]:
def lik_utenom_språkkode(nn_url, bm_url):
    biter = nn_url.split("nn-NO")
    biter2 = bm_url.split("nb-NO")
    return biter == biter2

par = []

for e in nynorske_url.itertuples():
    for e2 in bokmålske_url.itertuples():
        if lik_utenom_språkkode(e.url, e2.url):
            par.append((e.doc_hash, e2.doc_hash))

In [8]:
len(par)

55

In [9]:
import pprint
for nn_doc_hash, bm_doc_hash in par:
    pprint.pprint(list(nynorske[nynorske.doc_hash==nn_doc_hash].fulltext)[0][:6])
    pprint.pprint(list(bokmålske[bokmålske.doc_hash==bm_doc_hash].fulltext)[0][:6])
    print("\n________________________________\n")

['at inntekt og formue er lågare enn grensene',
 'Kva skal til for å få omgjering?',
 'Det vanlege studielånet som alle får, blir kalla basislån. Opptil 40 prosent '
 'av basislånet kan bli til stipend.',
 'Du må bu borte',
 'Du kan ikkje få gjort om lån til stipend for periodar du har budd heime hos '
 'foreldra dine. Når du søker om lån, oppgir du om du skal bu heime eller '
 'borte medan du studerer. Er du gift eller har barn du bur saman med, '
 'behandlar vi deg som bortebuar, sjølv om du bur hos foreldra dine.',
 'Du treng ikkje å endre adresse i folkeregisteret, men du kan bli bedt om å '
 'dokumentere at du faktisk har vore bortebuar.']
['at inntekt og formue er lavere enn grensene',
 'Hva skal til for å få omgjøring?',
 'Det vanlige studielånet som alle får, kalles basislån. Opptil 40 prosent av '
 'basislånet kan bli til stipend.',
 'Du må bo borte fra foreldrene dine',
 'Du kan ikke få gjort om lån til stipend for perioder du har bodd hjemme hos '
 'foreldrene dine. Når du søker om lån, oppgir du om du skal bo hjemme eller '
 'borte mens du studerer. Er du gift eller har barn du bor sammen med, '
 'behandler vi deg som borteboer, selv om du bor hos foreldrene dine.',
 'Du trenger ikke å endre adresse i folkeregisteret, men du kan bli bedt om å '
 'dokumentere at du faktisk har vært borteboer.']

________________________________

['VeilederInntektOgFormue',
 'Behovsprøving av stipend',
 'Har du inntekt eller formue over grensene, får du mindre stipend.',
 'I 2020, 2021 og 2022 har det vore eit unnatak frå inntektsgrensa for arbeid '
 'i nokre sektorar. Dette har vore på grunn av koronapandemien. Klikk her for '
 'å lese om det gjeld deg.',
 'Kva er behovsprøving?',
 'Behovsprøving betyr at det er inntekta og formuen din som bestemmer kor '
 'stort stipend du kan få. Vi vurderer kor stort stipend du kan få opp mot '
 'fastsette grenser for inntekt og formue. Er inntekta eller formuen din '
 'høgare enn grensene, har du rett til mindre stipend. Det er ulike reglar som '
 'gjeld for behovsprøving for elevar på vanleg vidaregåande skole og '
 'lærlingar, og for andre studentar, for eksempel i høgare utdanning.']
['Hva er behovsprøving?',
 'Behovsprøving betyr at det er inntekten og formuen din som bestemmer hvor '
 'stort stipend du kan få.',
 'Vi vurderer hvor stort stipend du kan få opp mot fastsatte grenser for '
 'inntekt og formue. Hvis inntekten eller formuen din er høyere enn grensene, '
 'har du rett til mindre stipend.',
 'Det er ulike regler som gjelder for behovsprøving for elever på vanlig '
 'videregående skole og lærlinger, og for andre studenter, for eksempel i '
 'høyere utdanning.',
 'Behovsprøving av stipend i videregående opplæring',
 'Går du på vanlig videregående skole, sjekker vi inntekten til foreldrene '
 'dine hvis du søker om inntektsavhengig stipend. Foreldreinntekten har ikke '
 'noen innvirkning på utstyrsstipendet eller borteboerstipendet.']

________________________________

['Forseinking, avbrot og endring i utdanninga',
 '60 sp',
 'før det påverkar retten til lån og stipend',
 'Når du stryk på eksamen',
 'Stryk du på eksamen, blir du fagleg forseinka. Det kan påverke om du har '
 'rett til lån og stipend seinare, og kor mykje lån du får gjort om til '
 'stipend.',
 'Eitt års fulltidsutdanning tilsvarer 60 studiepoeng. Du kan vere inntil 60 '
 'studiepoeng forseinka utan at det påverkar kor mykje lån og stipend du kan '
 'få. Er du forseinka med meir enn 60 studiepoeng, har du ikkje rett til lån '
 'og stipend. Men dersom det er spesielle grunnar til at du blei forseinka, '
 'kan du likevel ha rett til støtte.']
['Forsinkelse, avbrudd og endring i utdanningen',
 '60 sp',
 'før det påvirker retten til lån og stipend',
 'Når du stryker på eksamen',
 'Hvis du stryker på eksamen, blir du faglig forsinket. Det kan påvirke om du '
 'har rett til lån og stipend senere, og hvor mye lån du får gjort om til '
 'stipend.',
 'Ett års fulltidsutdanning tilsvarer 60 studiepoeng. Du kan være inntil 60 '
 'studiepoeng forsinket uten at det påvirker hvor mye lån og stipend du kan '
 'få. Er du forsinket med mer enn 60 studiepoeng, har du ikke rett til lån og '
 'stipend. Men dersom det er spesielle grunner til at du ble forsinket, kan du '
 'likevel ha rett til støtte.']

________________________________

['Tilleggslån',
 '104 340',
 'i året',
 'Tilleggslån for deg som er 30 år eller eldre',
 'Du kan få tilleggslån dersom du tar universitets- eller høgskoleutdanning, '
 'fagskole eller vidaregåande skole, og er 30 år eller eldre.',
 'Tilleggslånet på 104 340 er berre for studentar på fagskole, universitets- '
 'eller høgskoleutdanning. Tar du vidaregåande opplæring, kan du låne inntil '
 '52 170 kroner i året. Tilleggslånet kjem i tillegg til andre lån og stipend.']
['Tilleggslån',
 '104 340',
 'i året',
 'Tilleggslån for deg som er 30 år eller eldre',
 'Du kan få tilleggslån hvis du tar universitets- eller høgskoleutdanning, '
 'fagskole eller videregående skole, og er 30 år eller eldre.',
 'Tilleggslånet på 104 340 er bare for studenter på fagskole, universitets- '
 'eller høgskoleutdanning. Tar du videregående opplæring, kan du låne inntil '
 '52 170 kroner i året. Lånet kommer i tillegg til andre lån og stipend.']

________________________________

['Du kan få skolepengelån i normert tid for resten av utdanninga di, dersom du '
 'begynte på ei gradsutdanning på nett i Storbritannia før 2021',
 'Lærestaden må vere godkjende for støtte frå Lånekassen',
 'Nettstudium på ein norsk lærestad',
 'Du kan få lån og stipend etter dei same reglane som elevar og studentar som '
 'tar stadbasert utdanning.',
 'Kva for utdanningar er godkjende for lån og stipend?',
 'Nettstudium i Noreg blir godkjende for utdanningsstøtte etter dei same '
 'reglane som anna utdanning. Det betyr at nettstudium ved universitet og '
 'høgskolar som hovudregel gir rett til lån og stipend, så lenge utdanninga '
 'varar i minst eitt semester.']
['Du kan få skolepengelån i normert tid for resten av utdanningen din, hvis du '
 'begynte på en gradsutdanning på nett i Storbritannia før 2021',
 'Lærestedet må være godkjent for støtte i Lånekassen',
 'Nettstudier på et norsk lærested',
 'Du kan få lån og stipend etter de samme reglene som elever og studenter som '
 'tar stedbasert utdanning.',
 'Hvilke utdanninger er godkjent for lån og stipend?',
 'Nettstudier i Norge blir godkjent for utdanningsstøtte etter de samme '
 'reglene som annen utdanning. Det innebærer at nettstudier ved universiteter '
 'og høgskoler som hovedregel gir rett til lån og stipend, så lenge '
 'utdanningen varer i minst ett semester.']

________________________________

['Søknadsfristar',
 'Du må ha ein studieplass før du søker, og du kan tidlegast søke i midten av '
 'mai. Siste frist for å søke er',
 '15. november for heile året eller berre haustsemesteret',
 '15. mars for vårsemesteret',
 'Alle studentar får basislån',
 'Studentar i Norden kan få same lån og stipend som dei som studerer i Noreg.']
['Veileder norden helgrad',
 'Studere i et annet nordisk land',
 'Lånekassen tilbyr lån og stipend til deg som tar en hel grad eller '
 'enkeltemner.',
 'Utdanningen må være godkjent i landet du skal til',
 'Vi kan gi lån og stipend til universiteter og både private og offentlige '
 'høgskoler i alle de nordiske landene. Vilkåret er at utdanningen er '
 'offentlig godkjent i studielandet og godkjent for lån og stipend fra '
 '«Lånekassen» i det aktuelle landet.',
 'Søknadsfristen er 15. november hvis du skal ha støtte hele året']

________________________________

['Utveksling i eit anna nordisk land',
 'Søknadsfristar',
 'Du må ha ein studieplass før du søker, og du kan tidlegast søke i midten av '
 'mai. Siste frist for å søke er',
 '15. november for heile året eller berre haustsemesteret',
 '15. mars for vårsemesteret',
 'Utvekslinga må vere godkjent som ein del av utdanninga di']
['Veileder Norden utveksling',
 'Utveksling i et annet nordisk land',
 'Søknadsfrister',
 'Du må ha en studieplass før du søker, og du kan tidligst søke i midten av '
 'mai. Siste frist for å søke er',
 '15. november for hele året eller bare høstsemesteret',
 '15. mars for vårsemesteret']

________________________________

['Studere igjen',
 'Dersom du har lån i Lånekassen frå tidlegare og skal begynne å studere '
 'igjen, blir lånet sett rente- og avdragsfritt om du får lån og stipend til '
 'fulltidsutdanning.',
 'Inntektsgrenser for omgjering av lån til stipend',
 'Får du lån til utdanning frå oss, må du ha inntekt og formue under fastsette '
 'grenser for å få gjort om delar av lånet til stipend etter du har bestått '
 'utdanninga di. Er du gift eller har sambuar med felles barn, er det den '
 'felles formuen dykkar vi vurderer.',
 'Dei same grensene gjeld dersom du studerer på deltid, men då blir '
 'reduksjonen i stipend mindre om du tener over grensa.',
 'Kva skjer med studielånet når du begynner på ei ny utdanning?']
['Studere igjen',
 'Hvis du har lån i Lånekassen fra tidligere og skal begynne å studere igjen, '
 'blir lånet satt rente- og avdragsfritt hvis du får lån og stipend til '
 'fulltidsutdanning.',
 'Inntektsgrenser for omgjøring av lån til stipend',
 'Får du lån til utdanning fra oss, må du ha inntekt og formue under fastsatte '
 'grenser for å få gjort om deler av lånet til stipend etter du har bestått '
 'utdanningen din. Er du gift eller har samboer med felles barn, er det den '
 'felles formuen deres vi vurderer.',
 'De samme grensene gjelder hvis du studerer på deltid, men da blir '
 'reduksjonen i stipend mindre hvis du tjener over grensen.',
 'Hva skjer med studielånet når du begynner på en ny utdanning?']

________________________________

['Stipend og lån til yrkesutdanning i Norden',
 'Du kan få stipend og lån for å ta yrkesutdanning som er offentleg godkjent i '
 'det landet du skal flytte til og som gir rett til lån og stipend i dette '
 'landet.',
 'Kva blir rekna som yrkesutdanning?',
 'Du kan for eksempel få lån og stipend til å ta erhvervsutdanning i Danmark, '
 'yrkesutdanning (YH) og kommunal vaksenopplæring (komvux) i Sverige.',
 'Alle studentar får basislån og nokre får skolepengelån',
 'Dei fleste får to forskjellige typar lån til utdanning i Norden. Basislån og '
 'skolepengelån om du skal betale skolepengar.']
['Stipend og lån til yrkesutdanning i Norden',
 'Du kan få stipend og lån til å ta yrkesutdanning i andre nordiske land, hvis '
 'utdanningen er offentlig godkjent i det landet du skal flytte til, og gir '
 'rett til lån og stipend i dette landet.',
 'Hva regnes som yrkesutdanning?',
 'Du kan for eksempel få lån og stipend til å ta erhvervsutdanning i Danmark, '
 'yrkesutdanning (YH) og kommunal voksenopplæring (komvux) i Sverige.',
 'Alle studenter får basislån og noen får skolepengelån',
 'De fleste får to forskjellige typer lån til utdanning i Norden. Basislån og '
 'skolepengelån hvis du skal betale skolepenger.']

________________________________

['Folkehøgskole i Norden',
 'Lån og stipend for å gå på folkehøgskole i Norden',
 'Er du elev på ein folkehøgskole, kan du få lån og stipend i inntil ti '
 'månader.',
 'Studentar på folkehøgskole i Norden kan få basislån og i nokre tilfelle '
 'skolepengelån.',
 'Kva er basislån?',
 'Basislån er det alle studentar kan få, og er namnet på det dei fleste kallar '
 'studielån. 40% av basislånet kan bli gjort om til stipend seinare.']
['Folkehøgskole i Norden',
 'Lån og stipend for å gå på folkehøgskole i Norden',
 'Er du elev på en folkehøgskole, kan du få lån og stipend i inntil ti '
 'måneder.',
 'Studenter på folkehøgskole i Norden kan få basislån og i noen tilfeller '
 'skolepengelån.',
 'Hva er basislån?',
 'Basislån er det alle studenter kan få, og er navnet på det de fleste kaller '
 'studielån. 40% av basislånet kan gjøres om til stipend senere. Du får ikke '
 'ekstra lån og stipend til å dekke utgiftene ved linjen du skal gå på, eller '
 'til reise.']

________________________________

['Korte språkkurs',
 'Dersom du skal studere i utlandet på eit anna undervisningsspråk enn '
 'engelsk, dansk eller svensk, kan du få språkstipend til eit språkkurs.',
 'Både heil grad og utveksling',
 'Du kan få stipend til korte språkkurs enten du tar heile utdanninga i '
 'utlandet, eller om du skal på utveksling.',
 'Krav til korte språkkurs',
 'Kurset må vare i minst fire veker, med minimum 15 timer undervisning per '
 'veke. Det treng ikkje vere fire samanhengande veker, du kan få språkstipend '
 'til kombinasjonar av språkkurs som varer i minst fire veker til saman. Det '
 'er lengde på kurset som avgjer om du kan få støtte, ikkje studiepoeng.']
['Korte språkkurs',
 'Hvis du skal studere i utlandet på et annet undervisningsspråk enn engelsk, '
 'dansk eller svensk, kan du få språkstipend til et språkkurs.',
 'Både hel grad og utveksling',
 'Du kan få stipend til korte språkkurs enten du tar hele utdanningen i '
 'utlandet, eller om du skal på utveksling.',
 'Krav til korte språkkurs',
 'Kurset må vare i minst fire uker, med minimum 15 timer undervisning per uke. '
 'Det trenger ikke være fire sammenhengende uker, du kan få språkstipend til '
 'kombinasjoner av språkkurs som varer i minst fire uker til sammen. Det er '
 'lengde på kurset som avgjør om du kan få støtte, ikke studiepoeng.']

________________________________

['Renter og gebyrer',
 'Veileder renter',
 'Slik fungerer renter på studielånet',
 'Studielånet er rentefritt så lenge du får lån og stipend til '
 'fulltidsutdanning, eller dersom du får støtte til deltidsutdanning og ikkje '
 'har lån frå tidlegare.',
 'Det er ikkje slik at lånet er rentefritt så lenge du er student. Det er '
 'berre studentar som får lån eller stipend til fulltidsutdanning som har '
 'rentefritt lån. Frå dagen etter at du ikkje får støtte til fulltidsutdanning '
 'lenger, legg vi til renter på lånet ditt.',
 'Alle får flytande rente i utgangspunktet']
['Renter og gebyrer',
 'Veileder renter',
 'Slik fungerer renter på studielånet',
 'Studielånet er rentefritt så lenge du får lån og stipend til '
 'fulltidsutdanning, eller dersom du får støtte til deltidsutdanning og ikke '
 'har lån fra tidligere.',
 'Det er ikke slik at lånet er rentefritt så lenge du er student. Det er bare '
 'studenter som får lån eller stipend til fulltidsutdanning som har rentefritt '
 'lån. Fra dagen etter du ikke får støtte til fulltidsutdanning lenger, legger '
 'vi til renter på lånet ditt.',
 'Alle får flytende rente i utgangspunktet']

________________________________

['Du må ha uføretrygd',
 'Du må vere minst 50 prosent ufør. Dersom du fekk AAP '
 '(arbeidsavklaringspengar) frå Nav heilt fram til du fekk vedtak om '
 'uføretrygd, er det nok at du er minst 40 prosent ufør.',
 'Du kan søke om sletting av gjeld dersom du bur i utlandet og har fått '
 'innvilga ei yting i eit anna land som tilsvarer norsk uføretrygd. Du kan '
 'ikkje få uføretrygd frå folketrygda i Noreg.',
 'Dersom du har fylt 67 år og mottar alderspensjon, kan du ikkje søke om '
 'sletting av gjeld etter reglane for uføre.',
 'Vent med å søke til du har fått innvilga uføretrygd',
 'Du må ha fått innvilga uføretrygd hos folketrygda før du søker om sletting '
 'av gjeld hos Lånekassen. I mellomtida kan du bruke andre ordningar for '
 'betalingsletter. Du kan søke om sletting av renter dersom du har AAP, er '
 'sjuk eller er i ein annan situasjon som gir rett til sletting. Du kan også '
 'søke om betalingsutsetting.']
['Du må ha uføretrygd',
 'Du må være minst 50 prosent ufør. Hvis du fikk AAP (arbeidsavklaringspenger) '
 'fra Nav helt fram til du fikk vedtak om uføretrygd, er det nok at du er '
 'minst 40 prosent ufør.',
 'Hvis du bor i utlandet og ikke har uføretrygd fra folketrygden i Norge, kan '
 'du søke om sletting av gjeld hvis du har fått innvilget ytelse i et annet '
 'land som tilsvarer uføretrygd.',
 'Dersom du har fylt 67 år, og mottar alderspensjon, kan du ikke søke om '
 'sletting av gjeld etter reglene for uføre.',
 'Vent med å søke til du har fått innvilget uføretrygd',
 'Du må ha fått innvilget uføretrygd hos folketrygden før du søker om sletting '
 'av gjeld hos Lånekassen. I mellomtiden kan du benytte andre ordninger for '
 'betalingslettelser. Du kan søke om sletting av renter hvis du har AAP, er '
 'syk eller er i en annen situasjon som gir rett til sletting. Du kan også '
 'søke om betalingsutsettelse.']

________________________________

['Reduksjon av gjeld for deg i Finnmark og Nord-Troms',
 'Dersom du har budd og jobba i Finnmark eller utvalde kommunar i Troms i 12 '
 'månadar samanhengande, kan du få redusert gjelda di.',
 'Alle kundar som både bur og jobbar i områda som er godkjende, kan få sletta '
 'inntil 10 prosent av det opphavlege studielånet sitt kvart år, opptil ei '
 'grense på 25 000 kroner i året.',
 'Dersom du jobbar som lærar i grunnskolen, kan du få sletta ytterlegare 20 '
 '000 kroner i året.',
 'Du må bu og jobbe i regionen i minst 12 månader',
 'For å kunne få sletta gjeld, er det krav om at du må vere både busett og '
 'yrkesaktiv i Finnmark eller dei godkjende kommunane i Troms i ein '
 'oppteningsperiode på 12 månader. Vi reknar fleire enn berre heiltidstilsette '
 'som yrkesaktive. Du kan lese meir om krava her.']
['Reduksjon av gjeld for deg i Finnmark og Nord-Troms',
 'Hvis du har bodd og jobbet i Finnmark eller utvalgte kommuner i Troms i 12 '
 'måneder sammenhengende, kan du få redusert gjelden din.',
 'Alle kunder som både bor og jobber i områdene som er godkjente, kan få '
 'slettet inntil 10 prosent av det opprinnelige studielånet sitt hvert år, '
 'opptil en grense på 25 000 kroner i året.',
 'Hvis du jobber som lærer i grunnskolen, kan du få slettet ytterligere 20 000 '
 'kroner i året.',
 'Du må bo og jobbe i regionen i minst 12 måneder',
 'For å kunne få slettet gjeld, er det krav om at du må være både bosatt og '
 'yrkesaktiv i Finnmark eller de godkjente kommunene i Troms i en '
 'opptjeningsperiode på 12 måneder. Vi regner flere enn bare heltidsansatte '
 'som yrkesaktive. Les mer om kravene her.']

________________________________

['Lærarutdanning i realfag, framandspråk, samisk eller kvensk',
 'Dersom du fullfører visse lærarutdanningar i realfag, framandspråk, samisk '
 'eller kvensk, kan du få sletta inntil kr 50 000 av studielånet.',
 'Dersom du fyller vilkåra over, kan du få sletta gjeld med opptil 50 000 kr. '
 'Har du mindre gjeld enn 50 000, vil du få sletta resten av lånet ditt.',
 'Søknaden må vere kommen inn til Lånekassen seinast seks månader etter at '
 'eksamen er gjennomført.',
 'Realfag og framandspråk',
 'Du kan berre få sletta gjeld dersom faga er ein øvrig del av '
 'masterprogrammet. Følgjande program gjer rett til sletting:']
['Lærerutdanning i realfag, fremmedspråk, samisk eller kvensk',
 'Hvis du fullfører visse lærerutdanninger i realfag, fremmedspråk, samisk '
 'eller kvensk, kan du få slettet inntil 50 000 kroner av studielånet.',
 'Hvis du fyller vilkårene under, kan du få slettet gjeld med opptil 50 000 '
 'kroner. Hvis du har lavere gjeld enn 50 000 kroner, vil du få slettet resten '
 'av lånet ditt.',
 'Søknaden må ha kommet inn til Lånekassen senest seks måneder etter eksamen '
 'er gjennomført,',
 'Realfag og fremmedspråk',
 'Du kan bare få slettet gjeld når spesialiseringen din er i realfag eller '
 'fremmedspråk, ikke hvis fagene er en øvrig del av masterprogrammet. Disse '
 'programmene gir rett til å få slettet gjeld:']

________________________________

['Vi begynner å legge til renter på lånet ditt frå dagen etter støtteperioden '
 'din har gått ut. Har du for eksempel fått lån og stipend til og med 15. '
 'juni, legg vi renter på lånet frå og med 16. juni. Støtteperioden din finn '
 'du i vedtaksbrevet om lån og stipend som ligg i postkassen på Dine sider.',
 'Alle får flytande rente på lånet i utgangspunktet, og den flytande renta er '
 'den same for alle. Om du ønsker det, kan du søke om fast rente.',
 'Omtrent 7 månader etter studia',

In [10]:
with open("lanekassen_fasit.csv", "w+") as f:
    f.write("nynorsk_doc_hash,bokmål_doc_hash\n")
    f.write("\n".join([f"{nn_doc_hash},{bm_doc_hash}" for nn_doc_hash, bm_doc_hash in par]))