In [3]:
from pathlib import Path
import pandas as pd
import os

In [3]:
os.environ['MALFRID_2024'] = '/mnt/data/tita/målfrid_data/'

In [ ]:
from pathlib import Path
import pandas as pd
import os
import re

def extract_dfs(domain, lang_code):
    data_path_2024 = os.environ.get("MALFRID_2024", None)
    print(data_path_2024)
    source_p = Path(data_path_2024)
    out_p = Path(f"output/{domain}_{lang_code}.json")

    if not out_p.exists():
        filer = [e for e in source_p.iterdir() if domain in e.name and lang_code in e.name and "html" in e.name]
        if filer: 
            df = []
            for e in filer:
                with e.open("rb") as f:
                    df.append(pd.read_json(e, lines=True))
            df = pd.concat(df)
            df.index = range(len(df))
            df.to_json(out_p, index=False)
    df = pd.read_json(out_p)
    return df

df_nob = extract_dfs("lanekassen", "nob")
df_nno = extract_dfs("lanekassen", "nno")

/mnt/data/tita/målfrid_data/
/mnt/data/tita/målfrid_data/

In [113]:
df_nob

,doc_hash,lang,url,domain,date,mimetype,fulltext
0,d5cd8da3ce4a35c768ba3da023640da25dd189e1,nob,http://www.politiet.no/en/aktuelt-tall-og-fakt...,politiet.no,2023-12-19 04:24:29,html,[– Jeg må ha en stilling hvor jeg kan være nys...
1,2ddc475e43aefde9958c929263a7a23f55cdd0fe,nob,https://www.politiet.no/en/aktuelt-tall-og-fak...,politiet.no,2023-12-19 04:25:45,html,[Tre personer siktet etter innbrudd i Børselv ...
2,f1aaa6db3069f9cee3bddbf87dd842fb992c06b8,nob,https://www.politiet.no/en/aktuelt-tall-og-fak...,politiet.no,2023-12-19 04:26:15,html,"[Pressebrief på politihuset i Kristiansand, I ..."
3,2e3ceb9d55ca51181923165800a9a4216b2e5464,nob,http://www.politiet.no/en/tjenester/namsmann-o...,politiet.no,2023-12-19 04:30:45,html,"[Slik begjærer du tvangsdekning, Har du fått p..."
4,b833caedd0856e5844238089b9457c5b7efb4a54,nob,http://www.politiet.no/en/rad/menneskehandel/k...,politiet.no,2023-12-19 04:34:09,html,"[For tidligere års rapporter, ta kontakt med o..."
...,...,...,...,...,...,...,...
1060,a58a7d21b8e36fc8296d0c72c55b615720e3aac7,nob,https://www.politiet.no/om-politiet/organisasj...,politiet.no,2023-12-18 21:56:16,html,"[Jan Terje Aas, Enhet, Agder politidistrikt, J..."
1061,ff40055a0c5c63c2db48859fac95d6be639df753,nob,https://www.politiet.no/aktuelt-tall-og-fakta/...,politiet.no,2023-12-19 00:17:36,html,[GKI har gått fra å være noe for spesielt inte...
1062,e04d60a2f074207d5b4911a6951f268ada673b19,nob,https://www.politiet.no/en/om-politiet/organis...,politiet.no,2023-12-19 01:12:58,html,"[Farsund og Lyngdal politistasjon, Agder Polic..."
1063,9f675e19a361af3ace88b2dbd479e3364ddbd408,nob,https://www.politiet.no/en/om-politiet/organis...,politiet.no,2023-12-19 01:14:41,html,"[Måsøy politistasjon, Finnmark Police District..."
1064,8aa9e0998624d2f88707df9f33ad40985f70ce88,nob,https://www.politiet.no/en/om-politiet/organis...,politiet.no,2023-12-19 01:19:31,html,"[Tønsberg politistasjon, Southeastern Police D..."

In [114]:
df_nno

,doc_hash,lang,url,domain,date,mimetype,fulltext
0,b0524b86bc3fa3b34f53667fbbee6a45507c14da,nno,https://www.politiet.no/om-politiet/organisasj...,politiet.no,2023-12-18 20:17:04,html,"[Om oss, Sør-Vest politidistrikt dekker frå 1...."
1,3b5cce828a4402942e30e2120e8023e7ddc96dd2,nno,https://www.politiet.no/om-politiet/organisasj...,politiet.no,2023-12-18 20:42:58,html,"[Åpningstider, Førarkort og køyresetel, Kjøres..."
2,765d013d907323bcf1a1f8bda1c826b8a91c0ec3,nno,https://www.politiet.no/om-politiet/organisasj...,politiet.no,2023-12-18 20:43:03,html,"[Valldal mobilt pass– og ID-kontor, Møre og Ro..."
3,58f10a35082f0194934748cd751025906485b2f3,nno,https://www.politiet.no/om-politiet/organisasj...,politiet.no,2023-12-18 20:43:57,html,"[Mo i Rana politistasjon, Nordland politidistr..."
4,9d6a12e6220778e24dda140258fb4c6d0080e9db,nno,https://www.politiet.no/en/om-politiet/organis...,politiet.no,2023-12-19 01:17:25,html,"[Lurøy og Træna politistasjon, Nordland Police..."
...,...,...,...,...,...,...,...
185,0cdd79083d57b91cfb8c731df8ecfa7f118521a8,nno,https://www.politiet.no/om-politiet/organisasj...,politiet.no,2023-12-18 20:49:36,html,[Du kan søke om naudpass på politiposten i ter...
186,c7c1b8768d97c2a7eeb5115d22e4734eaa787a48,nno,https://www.politiet.no/om-politiet/organisasj...,politiet.no,2023-12-18 20:50:12,html,"[Lærdal mobilt pass– og ID-kontor, Vest politi..."
187,2f186e4a21ba1afc7a046ad2daf4ed26153f6ed3,nno,https://www.politiet.no/kontakt-politiet/innsy...,politiet.no,2023-12-18 21:43:12,html,"[Innsyn i Schengen informasjonssystem, Schenge..."
188,eb732290ad85f7f0ca028e368a44927ce0f0a12c,nno,https://www.politiet.no/en/om-politiet/organis...,politiet.no,2023-12-19 01:13:56,html,"[Timebestilling på nett, Bestill time på nett ..."
189,f5baa4901f46cdf30ec7bc4be0defa206b421aea,nno,https://www.politiet.no/en/om-politiet/organis...,politiet.no,2023-12-19 01:17:27,html,"[Mosjøen politistasjon, Nordland Police Distri..."

Fjern språkkode and sammenlign url med SequenceMatcher

In [119]:
import re
from difflib import SequenceMatcher
from collections import defaultdict
#from Levenshtein import distance

def extract_language_code(url):
    match = re.search(r'\/([a-z]{2}-[A-Z]{2}|nynorsk)\/', url)
    if match:
        return match.group(1)
    return None

def normalize_url(url):
    language_code = extract_language_code(url)
    if language_code:
        url = re.sub(r'\/[a-z]{2}-[A-Z]{2}\/', '/xx-XX/', url)
        print(url)
    return url

def compare_urls(url1, url2):
    normalized_url1 = normalize_url(url1)
    normalized_url2 = normalize_url(url2)

    similarity_score = SequenceMatcher(None, normalized_url1, normalized_url2).ratio()
    #similarity_score = Levenshtein.distance(normalized_url1, normalized_url2, weights=None, processor=None, score_cutoff=None, score_hint=None)
    return similarity_score

def write_matches(url1, url2):
    similarity_score = compare_urls(url1, url2)
    return similarity_score

threshold = 0.98
result_dict = defaultdict(list)
num_matches=0
for nn_row in df_nno.itertuples():
    for nb_row in df_nob.itertuples():
        nn_url = getattr(nn_row, 'url')
        nb_url = getattr(nb_row, 'url')
        
        similarity_score = write_matches(nn_url, nb_url)
        
        if similarity_score >= threshold:
            num_matches += 1
            
            result_dict["nynorsk_doc_hash"].append(getattr(nn_row, 'doc_hash'))
            result_dict["bokmaal_doc_hash"].append(getattr(nb_row, 'doc_hash'))
            result_dict["nynorsk_url"].append(nn_url)
            result_dict["bokmaal_url"].append(nb_url)
            result_dict["nynorsk_fulltext"].append(getattr(nb_row, 'fulltext'))
            result_dict["bokmaal_fulltext"].append(getattr(nb_row, 'fulltext'))

result_df = pd.DataFrame(result_dict)
print(f"Matches found: {num_matches}")

Matches found: 68

Fjern url-er som ender med et tall for å unngå dårlige matcher (feks  https://lanekassen.no/nn-NO/presse-og-samfunnskontakt/nyheiter/fastrentene-i-lanekassen-stiger2/ https://lanekassen.no/nn-NO/presse-og-samfunnskontakt/nyheiter/fastrentene-i-lanekassen-stiger3/)

In [116]:
def ends_with_digit(string):
    return string[-1].isdigit() if string else False

result_df_filtered = result_df[~result_df['nynorsk_url'].apply(ends_with_digit) & ~result_df['bokmaal_url'].apply(ends_with_digit)]

In [118]:
result_df_filtered.to_csv("output/politiet.csv", index=False)
print('Length after filtering', len(result_df_filtered))

Length after filtering 1