In [2]:
from pathlib import Path
import pandas as pd
from hemmelig import data_path

p = Path(data_path)

filer = [e for e in p.iterdir() if "lanekassen" in e.name]

dfs = []
for e in filer:
    with e.open("rb") as f:
        dfs.append(pd.read_json(e, lines=True))


df = pd.concat(dfs)
df

,doc_hash,lang,url,domain,date,mimetype,fulltext
0,b5fc6f81d5709f0051da1964c3900e7ca8df65f7,nno,http://lanekassen.no/globalassets/brosjyrer-fe...,lanekassen.no,2022-12-19 01:53:28+00:00,pdf,[Er du flyktning? Du blir rekna som flyktning ...
1,1fbe096fdfdd9916be1313006ac5cf44ac650231,nno,http://lanekassen.no/globalassets/skjemaer-fel...,lanekassen.no,2022-12-19 01:57:14+00:00,pdf,"[, , Du kan bruke dette skjemaet dersom du tar..."
2,582aaf9a510b3bde21b5b3e13ffc3453d6ca8174,nno,http://lanekassen.no/globalassets/skjemaer-fel...,lanekassen.no,2022-12-19 01:57:21+00:00,pdf,"[, , Det er viktig at du les informasjonen på ..."
3,32e23cf05e4db850a9e2f622c2edd0482572677e,nno,http://lanekassen.no/globalassets/skjemaer-fel...,lanekassen.no,2022-12-19 02:00:45+00:00,pdf,[Nynorsk Skjema for lærlinglønn Kor stort bort...
4,4ea46648c7ce59fe0c39b45779ed6402d8b41369,nno,http://lanekassen.no/globalassets/skjemaer-fel...,lanekassen.no,2022-12-19 02:01:01+00:00,pdf,[Nynorsk Skjema I – artikkelnr. 9001550 – nyno...
...,...,...,...,...,...,...,...
72,e29a43da7165d92d937c56416d50f563201ab5fa,nob,http://lanekassen.no/siteassets/skjemaer-og-fi...,lanekassen.no,2022-12-19 02:50:18+00:00,pdf,"[, , 01.01.2020 Storebrand Bank ASA 70 % Bolig..."
73,c120ee7f582c758ae392b8f90795a7c664c39e90,nob,http://lanekassen.no/siteassets/skjemaer-og-fi...,lanekassen.no,2022-12-19 02:50:23+00:00,pdf,"[, , 06.11.2019 Storebrand Bank ASA 70 % Bolig..."
74,553101a9b0a9fac935cf31e5dd59555d23ecbefe,nob,https://statistikk.lanekassen.no/globalassets/...,lanekassen.no,2022-12-19 03:10:41+00:00,pdf,"[, , Flyktningstipendet Mottakere av flyktning..."
75,1f14c7bcc564613f79be7a8cae1a946e27cfd755,nob,https://statistikk.lanekassen.no/globalassets/...,lanekassen.no,2022-12-19 03:10:44+00:00,pdf,"[, , Tall og fakta om Lånekassens kunder og or..."
76,ad84c32284570d5883b5c12276961d0a74ec1649,nob,https://statistikk.lanekassen.no/globalassets/...,lanekassen.no,2022-12-19 03:10:46+00:00,pdf,[Bruk av studiestøtte blant studenter med innv...

In [2]:
nynorske = df[df.lang == "nno"]
nynorske.index = range(len(nynorske))

bokmålske = df[df.lang == "nob"]
bokmålske.index = range(len(bokmålske))

len(nynorske), len(bokmålske)

(256, 310)

In [3]:
from sentence_transformers import SentenceTransformer, util

model = SentenceTransformer('NbAiLab/nb-sbert-base', device="cuda")

In [14]:
nynorske_sents = [(e.doc_hash, sent) for e in nynorske.itertuples() for sent in e.fulltext if sent]
nynorske_sents = pd.DataFrame(nynorske_sents, columns=["doc_hash", "sentence"])
nynorske_sents = nynorske_sents.drop_duplicates("sentence")
nynorske_sents.index = range(len(nynorske_sents))
nynorske_sents

,doc_hash,sentence
0,b5fc6f81d5709f0051da1964c3900e7ca8df65f7,Er du flyktning? Du blir rekna som flyktning d...
1,b5fc6f81d5709f0051da1964c3900e7ca8df65f7,Kor mykje pengar kan du få? Går du i vidaregåa...
2,b5fc6f81d5709f0051da1964c3900e7ca8df65f7,Grunnskoleopplæring for vaksne. Opplæring som ...
3,b5fc6f81d5709f0051da1964c3900e7ca8df65f7,Bruk søknaden for høgare og annan utdanning. B...
4,b5fc6f81d5709f0051da1964c3900e7ca8df65f7,Flyktningstipend: 58 585 kroner per semester. ...
...,...,...
4027,040c243fcce7c03c8d0f717d6883b66334f2c811,Publisert 27. januar 2022: Kva kjenneteiknar d...
4028,040c243fcce7c03c8d0f717d6883b66334f2c811,Dette er hovudfunna:
4029,040c243fcce7c03c8d0f717d6883b66334f2c811,Delen oppsagte studielån synk Lånekassen har n...
4030,040c243fcce7c03c8d0f717d6883b66334f2c811,"Oftare unge, menn og oftare født i utlandet De..."
4031,040c243fcce7c03c8d0f717d6883b66334f2c811,Oppseiing tidleg i «tilbakebetalingskarrieren»...

In [15]:
bokmål_sents = [(e.doc_hash, sent) for e in bokmålske.itertuples() for sent in e.fulltext if sent]
bokmål_sents = pd.DataFrame(bokmål_sents, columns=["doc_hash", "sentence"])
bokmål_sents = bokmål_sents.drop_duplicates("sentence")
bokmål_sents.index = range(len(bokmål_sents))
bokmål_sents

,doc_hash,sentence
0,6d87f8f74ffbd771311bf08814f8434f39101785,Universitet og høgskole
1,6d87f8f74ffbd771311bf08814f8434f39101785,Her finner du informasjon om hvor mye lån og s...
2,6d87f8f74ffbd771311bf08814f8434f39101785,Hoyskole og universitet i Norge
3,6d87f8f74ffbd771311bf08814f8434f39101785,Studere i Norge
4,6d87f8f74ffbd771311bf08814f8434f39101785,Studier ved alle universiteter og godkjente hø...
...,...,...
6447,ad84c32284570d5883b5c12276961d0a74ec1649,"Opheim, V. (2002), Kostbar kunnskap. Fordeling..."
6448,ad84c32284570d5883b5c12276961d0a74ec1649,Modell 1 Modell 2 Modell 3 Modell 4 Innvandrer...
6449,ad84c32284570d5883b5c12276961d0a74ec1649,"når 16 år Årlig yrkesinntekt -0,008 (0,000) An..."
6450,ad84c32284570d5883b5c12276961d0a74ec1649,Modell 1 Modell 2 Modell 3 Modell 4 Innvandrer...
6451,ad84c32284570d5883b5c12276961d0a74ec1649,"e fag Helse-, sosial- og idrettsfag -6 348,3 (..."

# Dokumentalignment ved hjelp av setningsalignment

In [4]:
# nynorsk_sentences = [sent for e in nynorske.itertuples() for sent in e.fulltext if sent]
# nynorsk_sent_to_doc_indexer = {}

# sent_i = 0
# for e in nynorske.itertuples():
#     for sent in e.fulltext:
#         if sent:
#             assert nynorsk_sentences[sent_i] == sent 
#             nynorsk_sent_to_doc_indexer[sent_i] = e.Index
#             sent_i += 1

# bokmål_sentences = [sent for e in bokmålske.itertuples() for sent in e.fulltext if sent]
# bokmål_sent_to_doc_indexer = {}

# sent_i = 0
# for e in bokmålske.itertuples():
#     bm_index = len(nynorske) + e.Index
#     for sent in e.fulltext:
#         if sent:
#             assert bokmål_sentences[sent_i] == sent 
#             bokmål_sent_to_doc_indexer[sent_i] = bm_index
#             sent_i += 1

In [16]:
nynorsk_embeddings = model.encode(list(nynorske_sents.sentence))
bokmål_embeddings = model.encode(list(bokmål_sents.sentence))

search_result = util.semantic_search(nynorsk_embeddings, bokmål_embeddings, top_k=1)
threshold = 0.95
matches = [(i, e[0]) for i, e in enumerate(search_result) if e[0]["score"] > threshold]

In [19]:
nynorske_sents.iloc[0].doc_hash

'b5fc6f81d5709f0051da1964c3900e7ca8df65f7'

In [20]:
doc_edges = [(nynorske_sents.iloc[nynorsk_sent_i].doc_hash, bokmål_sents.iloc[match["corpus_id"]].doc_hash) for nynorsk_sent_i, match in matches]

In [ ]:
import networkx as nx
from pyvis.network import Network

G = nx.DiGraph()

for nynorsk_sent_i, match in matches:
    bokmål_sent_i = match["corpus_id"]

    nn_doc_i = nynorsk_sent_to_doc_indexer[nynorsk_sent_i]
    bm_doc_i = bokmål_sent_to_doc_indexer[bokmål_sent_i]

    nn_text = nynorsk_sentences[nynorsk_sent_i]
    bm_text = bokmål_sentences

    G.add_node(nn_doc_i, color="green")
    G.add_node(bm_doc_i, color="purple")
    G.add_edge(nn_doc_i, bm_doc_i)

#nx.draw(G)

nt =  Network('1000px', '2000px')
nt.from_nx(G)
nt.show("basic.html", notebook=False)

basic.html

In [ ]:
comps = nx.weakly_connected_components(G)
pairs = [e for e in comps if len(e) == 2]
duplicates = len(nynorsk_sentences) - len(nynorsk_texts_flat)

print(f"""
Det er {len(pairs)} nynorsk-dokumenter som kun er koblet til ett bokmåls-dokument
Det er altså {len(nynorske)-len(pairs)} dokumenter på nynorsk som kobles til mer ennb ett bokmåls-dokument
Av totalt {len(nynorsk_sentences)} nynorske setninger, er det {len(nynorsk_texts_flat)} unike. 
Altså er {duplicates} av setningene duplikater, eller {round(duplicates/len(nynorsk_sentences)*100, 2)}% 
""")

Det er 94 nynorsk-dokumenter som kun er koblet til ett bokmåls-dokument
Det er altså 162 dokumenter på nynorsk som kobles til mer ennb ett bokmåls-dokument
Av totalt 5018 nynorske setninger, er det 4032 unike.
Altså er 986 av setningene duplikater, eller 19.65%

## Forsøker å bygge en graf uten duplikater

In [ ]:
Counter(nynorsk_sentences).most_common()

[('Merknad', 118),
 ('Dokumentasjon', 21),
 ('x x x x x x', 19),
 ('Behandlingstid', 19),
 ('x', 15),
 ('Tilleggslån', 15),
 ('Dette søker du om', 15),
 ('Barnestipend', 14),
 ('Slik søker du', 13),
 ('x x', 12),
 ('Har du barn?', 12),
 ('Foreldrestipend ved fødsel eller adopsjon', 12),
 ('Får du barn medan du studerer, kan du få gjort om basislån og skolepengelån til stipend i inntil 49 veker.',
  12),
 ('Dersom du har barn under 16 år, kan du få ekstra stipend. Har du fleire barn, får du meir stipend. Barnestipendet blir behovsprøvd, det betyr at beløpet blir mindre om familien har inntekt eller formue over grensene i forskrifta. Dersom du studerer på deltid, får du også eit lågare beløp.',
  12),
 ('Du kan også låne 52 170 kroner ekstra i året når du har barn under 16 år, avgrensa til 104 340 kroner til saman. Inntekt og formue har inga betydning for om du kan få tilleggslån. Men dersom du studerer på deltid, får du tilbod om å låne eit mindre beløp.',
  12),
 ('Det er eigne søknader for foreldrestipend og for tilleggsstipend ved nedsett funksjonsevne.',
  12),
 ('x x x', 11),
 ('15. november for heile året eller berre haustsemesteret', 11),
 ('15. mars for vårsemesteret', 11),
 ('x x x x x', 10),
 ('Er du over 30 år?', 10),
 ('Du kan søke om inntil', 10),
 ('I dei fleste tilfelle krevst det ikkje dokumentasjon for studium i Noreg. Må du likevel sende dokumentasjon, får du beskjed om det i søknaden. Etter at du har søkt, kan du sende dokumentasjonen til oss på Dine sider på lanekassen.no eller i posten.',
  10),
 ('Du får svar, eller beskjed om status for søknaden, innan 24 timar.', 10),
 ('Søknaden er ikkje synleg på Dine sider med éin gong, men så lenge du har fått kvittering, har vi fått søknaden din. På Dine sider får du også informasjon om anslått behandlingstid for søknaden din.',
  10),
 ('Merknad til bokstav f', 10),
 ('Søknadsfristar', 9),
 ('104 340', 9),
 ('Har du nedsett funksjonsevne?', 8),
 ('Du kan søke om', 8),
 ('ekstra stipend', 8),
 ('om du ikkje kan jobbe ved sidan av', 8),
 ('Dersom du har nedsett funksjonsevne som gjer at du ikkje kan jobbe ved sidan av utdanninga kan du få eit tilleggsstipend på 4 000 kroner i månaden. Dersom du studerer på deltid, får du eit mindre beløp.',
  8),
 ('Du kan også få stipend og lån om sommaren om du ikkje kan jobbe i sommarferien. Ein fagspesialist må bekrefte at du har nedsett funksjonsevne.',
  8),
 ('Du søker om lån og stipend ved nedsett funksjonsevne på eit eige skjema.',
  8),
 ('i tilleggslån per år', 8),
 ('Du kan låne inntil 104 340 kroner ekstra i året dersom du studerer på fulltid, som er 60 studiepoeng per år. Tar du færre studiepoeng, får du tilbod om å låne eit mindre beløp. Du kan låne 208 680 kroner til saman, og du kan velje kor mange år du vil fordele lånet over. Du søker om lånet i den same søknaden som vanleg lån og stipend.',
  8),
 ('Dokumentasjonskrav', 8),
 ('Merknad til bokstav a', 8),
 ('Skolepengar', 7),
 ('Lånet må betalast tilbake', 6),
 ('I søknaden søker du om basislån og eventuelt skolepengelån. Du kan velje å søke om berre den delen av basislånet som kan bli gjort om til stipend, eller heile lånet.',
  6),
 ('Søknaden gjeld også for andre stipend og lån som berre somme har krav på. Dette er barnestipend, tilleggslån og flyktningstipend.',
  6),
 ('Kundenummer i Lånekassen Fødselsnummer (11 siffer) Etternamn Fornamn og mellomnamn',
  5),
 ('x x x x', 5),
 ('Lånet er rentefritt så lenge du får lån til fulltidsutdanning', 5),
 ('Du må ha ein studieplass før du søker, og du kan tidlegast søke i midten av mai. Siste frist for å søke er',
  5),
 ('Er du over 18 år og vil ta opp lån?', 5),
 ('Dersom du er over 18 år og ikkje bur saman med foreldra dine, kan du låne inntil 3 467 kroner i månaden.',
  5),
 ('Lånet blir ikkje behovsprøvd mot inntekt. Det betyr at du kan få lånet uavhengig av kor mykje du eller foreldra dine tener.',
  5),
 ('Dette er eit lån som du må betale tilbake. Når du ikkje lenger får stipend og lån frå Lånekassen, blir det lagt til renter på lånet, og du må betale tilbake. Du må betale heile lånet pluss renter, men du betaler ned i månadlege avdrag.',
  5),
 ('Det er ikkje ein eigen søknad om lån. Når du søker om vanleg stipend og kryssar av for at du bur borte, får du spørsmål om du vil søke om lån også.',
  5),
 ('Alle studentar får basislån', 4),
 ('Kor mykje kan eg tene?', 4),
 ('40 prosent av basislånet kan bli stipend', 4),
 ('Kor mykje kan eg få?', 4),
 ('Gjeld og nedbetaling', 4),
 ('Vi hentar som regel opplysningar om utvekslingsopphaldet elektronisk når du søker om støtte, men i enkelte tilfelle må du likevel sende inn dokumentasjon.',
  4),
 ('Grensene for formue og trygd gjeld framleis', 4),
 ('I søknaden søker du om basislån, reisestøtte og eventuelt skolepengestøtte. Du kan velje å søke om stipend, og då får du berre stipenddelen av skolepengestøtta og reisestøtta, i tillegg til den delen av basislånet som kan bli gjort om til stipend',
  4),
 ('- barn av låntakaren sin ektefelle som bur saman med låntakaren minst 40 prosent av tida',
  4),
 ('Merknad til bokstav c', 4),
 ('Merknad til bokstav d', 4),
 ('Merknad til bokstav b', 4),
 ('Lånekassen behandlar personopplysningar i samsvar med regelverket for personvern.',
  3),
 ('Busette i regionen med eit arbeid som gjer at dei må utføre arbeid både i og utanfor regionen, kan bli vurderte etter denne regelen.',
  3),
 ('Ein låntakar som har misleghalde betalingspliktene sine overfor Lånekassen, slik at lånet er oppsagt på tidspunktet for ettergiving, kan få rett til ettergiving for den delen av lånet som ikkje har forfalle til betaling, dersom det er inngått ein betalingsavtale som blir følgd.',
  3),
 ('Krav som blir overførte til Statens innkrevjingssentral, får lagt til renter etter den rentesatsen som blir fastsett for lån i Lånekassen etter §§ 2-3 og 2-4.',
  3),
 ('Låntakarar med økonomiske vanskar kan søkje om gjeldsordning etter gjeldsordningsloven. Søknaden skal rettast til Statens innkrevjingssentral.',
  3),
 ('x x x x x x x x', 3),
 ('x x x x x x x x x x', 3),
 ('For at lånet skal vere rente- og avdragsfritt, må du få studielån til fulltidsutdanning. Når du ikkje lenger får studielån, eller går frå å studere på fulltid til deltid, blir det lagt til renter på lånet, og du må begynne å betale. Det tar cirka sju månader frå du sist fekk studielån frå oss, til du får den første rekninga.',
  3),
 ('I tillegg til at du må bestå utdanninga di, er det også eit krav om å ikkje tene for mykje. Merk at inntektsgrensene gjeld for kalenderåret og ikkje studieåret. Får du støtte for berre eitt semester, er grensa høgare.',
  3),
 ('Du mister ikkje heile stipendet om du har inntekt litt over grensa, men vi reduserer det gradvis etter kor stor inntekt du har hatt.',
  3),
 ('Vi ser også på trygd og formue.', 3),
 ('Formue og trygdeinntekter kan også påverke kor mykje av basislånet som kan bli til stipend.',
  3),
 ('For at lånet skal vere rente- og avdragsfritt, må du få studielån til fulltidsutdanning. Når du ikkje lenger får studielån, eller går frå å studere på fulltid til deltid, blir det lagt til renter på lånet, og du må begynne å betale.',
  3),
 ('Når kan du søke', 3),
 ('Les meir Lukk feltet', 3),
 ('Du får ikkje stipend på same måten som på vidaregåande, men inntil 40 prosent av lånet kan bli stipend seinare.',
  3),
 ('Du må betale tilbake lånet når du er ferdig med utdanninga', 3),
 ('Når du ikkje lenger får lån til fulltidsutdanning, får du ein betalingsplan og må begynne å betale avdrag. Den første rekninga skal betalast omtrent sju månader etter den siste utbetalinga frå oss.',
  3),
 ('Lånet er rentefritt berre så lenge du får lån eller stipend til fulltidsutdanning.',
  3),
 ('Fullfører du skoleåret og har inntekt og formue under grensene, blir 40 prosent av lånet gjort om til stipend. Det betyr at du ikkje treng å betale det tilbake. Du får eit eige vedtak frå oss når lånet blir gjort om.',
  3),
 ('Bur du heime hos foreldra dine, får du ikkje stipend', 3),
 ('Det er berre bortebuarar som kan få gjort om lån til stipend. Dersom du bur på internat, reknar vi deg som bortebuar.',
  3),
 ('Les meir Lukk', 3),
 ('Lån frå Lånekassen er rente- og avdragsfritt så lenge du er student og får støtte frå oss. Når du ikkje lenger får støtte til fulltidsutdanning frå Lånekassen, blir det lagt til renter på lånet og du må begynne å betale rundt 9 månader seinare.',
  3),
 ('Omgjering av lån til stipend', 3),
 ('Basislån kan alle studentar få, og dette er namnet på det dei fleste kallar studielån. Basislånet er eit lån, ikkje et stipend, men inntil 40 prosent av dette lånet kan bli gjort om til stipend dersom du ikkje bur saman med foreldra dine, du består utdanninga di og har inntekt og formue under grensene.',
  3),
 ('Stipend til skolepengar', 3),
 ('Du kan få stipend til å betale delar av skolepengane. Stipendet er på inntil 85 prosent av skolepengane, men det er øvre grense på 100 818 kroner per år.',
  3),
 ('Du får berre stipendet til reine skolepengar, men ikkje for eksempel programavgift til utvekslingsorganisasjonen. Skolen må stadfeste at du betaler skolepengar.',
  3),
 ('Lån til skolepengar', 3),
 ('Basislån', 3),
 ('Betalingsutsetting', 3),
 ('Søknadsfrist', 3),
 ('Skal du studere ved to ulike lærestader, må du velje den eine skolen i søknaden, og sende inn dokumentasjon for den andre skolen etterpå.',
  3),
 ('Unntaket gjeld berre for studentar som får lån og stipend til høgare og anna utdanning i Noreg og utlandet.',
  3),
 ('Du må dokumentere arbeidet', 3),
 ('Dersom du har fått eit vedtak om at inntekta di er over grensa for stipend, vil du få saka behandla på nytt dersom du sender oss lønnsslippar som viser:',
  3),
 ('inntekta i perioden', 3),
 ('Når vi får dokumentasjonen frå deg, vurderer vi inntekta di på nytt, og du får eit nytt vedtak.',
  3),
 ('Frist for å sende oss dokumentasjon', 3),
 ('Du sender inn dokumentasjonen så snart du har fått vedtak om kontroll av inntekt og formue. Klagefristen på tre veker gjeld ikkje for å sende inn nye opplysningar om koronarelatert arbeid, berre for andre forhold ved vedtaket.',
  3),
 ('Studentar som har barn', 3),
 ('Dette må du sende', 3),
 ('Kva skal eg rapportere?', 3),
 ('Ni av ti har flytande rente', 3),
 ('Du må sende inn', 3),
 ('Samtykke', 3),
 ('I søknaden blir du spurd om å samtykke til at vi hentar informasjon frå Vigo. Dersom du samtykker, hentar vi informasjon om kva skole og utdanningsprogram du skal ta. Dersom du ikkje samtykker, må du velje utdanningsprogram og skole frå ei liste.',
  3),
 ('Årets søknad 2022–2023', 3),
 ('Stad/dato Underskrift', 2),
 ('Lånekassen sender ut ein betalingsplan når lånet er gjort renteberande etter § 2-1. Ein låntakar som har fått betalingsplan og deretter har fått lån eller stipend til ny utdanning, får ny betalingsplan for den samla gjelda.',
  2),
 ('Låntakarar som har flytande rente, kan innfri gjelda eller betale ned raskare og med større beløp enn det som er fastsett i betalingsplanen, utan ekstra kostnader. For låntakarar som har fast rente etter § 2-5, vil ekstra innbetaling i avtaleperioden føre til at det blir rekna rentetap eller rentegevinst etter § 2-7 og § 2-8. Ekstra innbetalingar kan berre refunderast i særlege tilfelle. Kundar som har lån som skal bli gjort om til stipend, og som innfrir heile gjelda før siste omgjering er utført, kan få refundert stipendbeløpet. Dette gjeld berre for kundar som har fått støtte i den perioden som blir behovsprøvd.',
  2),
 ('Utdanningsgjelda skal nedbetalast månadleg. Låntakaren får den første rekninga om lag sju månader etter at lånet er gjort renteberande, sjå § 2-1. Ein låntakar som får lån eller stipend til deltidsutdanning og allereie har ein betalingsplan for lån, skal betale etter denne planen. Når låntakaren ikkje lenger får lån eller stipend, får han eller ho ny betalingsplan for heile gjelda. Låntakaren får ikkje nokon betalingspause som nemnd i andre leddet. Terminbeløpet skal betalast sjølv om låntakaren ikkje har fått rekninga.',
  2),
 ('Dersom låntakaren ikkje betaler heile det ubetalte terminbeløpet, kan Statens innkrevjingssentral og låntakaren inngå betalingsavtale for det forfalne beløpet.',
  2),
 ('Ordninga omfattar låntakarar som har fullført ei av desse utdanningane: a)integrert masterprogram i lærarutdanning med spesialisering i realfag b)toårig fagdidaktisk masterprogram for lærarar som tek spesialisering i realfag c)praktisk-pedagogisk utdanning, etter fullført mastergrad eller hovudfag i biologi, fysikk, geofag, informasjonsteknologi, kjemi, matematikk eller teknologiske fag eller fullført sivilingeniørutdanning d)praktisk-pedagogisk utdanning, etter fullført ingeniørutdanning.',
  2),
 ('Ordninga omfattar låntakarar som har fullført ei av desse utdanningane: a)integrert masterprogram i lærarutdanning med spesialisering i framandspråk b)toårig fagdidaktisk masterprogram for lærarar som tek spesialisering i framandspråk c)praktisk-pedagogisk utdanning, etter fullført mastergrad eller hovudfag i framandspråk. Nordisk og norsk blir ikkje rekna som framandspråk etter denne ordninga.',
  2),
 ('Søknad om sletting av gjeld må vere kommen inn til Lånekassen seinast seks månader etter at låntakaren har teke siste eksamen i den utdanninga som gir grunnlag for sletting av gjeld. Lånekassen kan gjere unntak frå fristen dersom det er særlege grunnar til at søknadsfristen ikkje kan bli halden.',
  2),
 ('Fastsett av Kunnskapsdepartementet 19. desember 2017 med heimel i lov 3. juni 2005 nr. 37 om utdanningsstøtte (utdanningsstøtteloven) §§ 8, 9, 10, 14 og 15.',
  2),
 ('Statens innkrevjingssentral kan slette lån, renter og kostnader dersom låntakaren har varig sterkt nedsett betalingsevne. Låntakaren kan ikkje få sletta gjeld dersom det vil verke støytande overfor andre låntakarar og samfunnet elles. Ein søknad om sletting av gjeld skal ha med dokumenterte opplysningar om inntekta, formuen, gjelda, og levekostnadene til låntakaren, og det skal stå kor mange barn han eller ho har. Søknaden skal innehalde tilsvarande opplysningar om ektefellen eller sambuaren i tillegg til anna som kan ha noko å seie for saka. Døyr låntakaren, blir gjelda sletta.',
  2),
 ('Låntakaren har ikkje rett til å klage etter reglane i forvaltningsloven på avgjerder i saker om sletting av gjeld på grunn av varig sterkt nedsett betalingsevne.',
  2),
 ('Dersom ein låntakar med vilje eller aktlaust har brote opplysningsplikta og såleis har fått eller prøvd å få utbetalt eller godskrive lån eller stipend som han eller ho ikkje har rett til, kan låntakaren misse retten til sletting av renter, betalingsutsetjing og sletting av gjeld. Lånekassen kan krevje beløpet tilbakebetalt og rekne renter frå det tidspunktet låntakaren fekk tildelt lån eller stipend. Heile gjelda kan seiast opp og krevjast inn. Dersom ein låntakar med vilje eller aktlaust har brote opplysningsplikta og såleis har fått sletta renter eller gjeld som han eller ho ikkje har rett til, kan låntakaren misse retten til betalingsutsetjing og sletting av renter og gjeld. I vurderinga av misleghaldet skal hovudvekta leggjast på kor lenge misleghaldet har vart, og kor mykje urettkommen lån eller stipend eller sletting av renter eller gjeld låntakaren har fått.',
  2),
 ('Misleghald av betalingsplikta kan føre til avslag på søknad om lån eller stipend til ny utdanning etter forskrift om tildeling av utdanningsstøtte, og avslag på søknad om betalingsutsetjing, sletting av renter og gjeld.',
  2),
 ('Bulder Bank (Sparebanken Vest) Boliglån innenfor 55 % Hver bank telles kun 1 gang Bulder Bank (Sparebanken Vest) Boliglån innenfor 60 % Hver bank telles kun 1 gang NORDirekte (Skagerrak Sparebank) Boliglån inntil 60 % Hver bank telles kun 1 gang Bulder Bank (Sparebanken Vest) Boliglån innenfor 65 % Hver bank telles kun 1 gang',
  2),
 ('Alle program', 2),
 ('x x x x x x x x x', 2),
 ('x x x x x x x x x x x x x x', 2),
 ('Misleghald av studiegjeld Kjenneteikn ved lånekassekundar som får studielånet sitt oppsagt Ein analyse i samarbeid med Skatteetaten',
  2),
 ('Basislån kan alle studentar få, og dette er namnet på det dei fleste kallar studielån. Basislånet er eit lån, ikkje eit stipend, men inntil 40 prosent av dette lånet kan bli gjort om til stipend dersom du ikkje bur saman med foreldra dine, du består utdanninga di og har inntekt og formue under grensene.',
  2),
 ('Dei aller fleste søknadane blir behandla i løpet av eit døgn, men meir kompliserte saker kan det ta lang tid å behandle. Pass på å søke så tidleg som mogleg, slik at du har pengane på konto når semesteret begynner.',
  2),
 ('Viktig å bestå utdanninga', 2),
 ('Når du får lån frå Lånekassen, er det eit krav at du skal bestå utdanninga. Består du mindre utdanning enn du har fått lån til, har det konsekvensar for om du kan få meir stipend og lån seinare, og kor mykje lån som blir gjort om til stipend.',
  2),
 ('Kven har ikkje ungdomsrett?', 2),
 ('Fagskole', 2),
 ('Kva er basislån?', 2),
 ('Dei aller fleste søknadene blir behandla i løpet av eit døgn, men meir kompliserte saker kan ta lang tid å behandle. Pass på å søke så tidleg som råd, slik at du har pengane på konto når semesteret begynner.',
  2),
 ('Deltid eller kortare studieår?', 2),
 ('Du får', 2),
 ('mindre lån', 2),
 ('dersom du studerer på deltid.', 2),
 ('Når får eg pengane?', 2),
 ('Du får større', 2),
 ('utbetalingar i', 2),
 ('Du tar opp lån når du går på folkehøgskole', 2),
 ('Når du går på folkehøgskole, får du lån og stipend etter dei same reglane som gjeld for høgare utdanning. Det er nokre forskjellar frå det å få stipend til vidaregåande, som det kan vere greitt å vite om.',
  2),
 ('Omgjeringa skjer først året etter at du er ferdig', 2),
 ('Lånet blir ikkje gjort om til stipend før vi har kontrollert inntekta og formuen din. Det gjer vi først når skatteoppgjeret ditt er klart for året eller åra du fekk lånet frå oss.',
  2),
 ('Det betyr at dersom du er ferdig med eit år på folkehøgskole våren 2022, får du ikkje gjort om lån til stipend før våren/sommaren 2023.',
  2),
 ('Skal du betale skolepengar?', 2),
 ('Omgjeringa skjer først året etter at du er ferdig.', 2),
 ('Det er berre bortebuarar som kan få gjort om lån til stipend.', 2),
 ('I 2022 er grensa', 2),
 ('Sjukdom', 2),
 ('Tilleggslån for deg som er 30 år eller eldre', 2),
 ('Det årlege maksimalbeløpet gjeld for fulltidsutdanning. Studerer du på deltid, blir beløpet redusert. Kor mykje du får når du studerer på deltid, avheng av kor mange studiepoeng eller årstimar du tar.',
  2),
 ('Kor mykje kan du låne til saman?', 2),
 ('Tilleggslån for deg som har barn', 2),
 ('Søknadsfrist 15. januar 2023', 2),
 ('Vi sjekkar ikkje om du har rett til straumstipendet når vi behandlar søknaden og utbetaler pengane. Det betyr at vi gir deg straumstipendet basert på eigenerklæringa i søknaden.',
  2),
 ('vere bortebuar', 2),
 ('For deg som tar grunnskolelærarutdanning 1-7', 2),
 ('Dersom du fullfører grunnskolelærarutdanning trinn 1-7, kan du få sletta 106 000 kroner av studielånet ditt. Vilkåra er at du fullfører studia på normert tid og at du har jobba som lærar i minst tre av dei første seks åra etter at du har fullført utdanninga.',
  2),
 ('For deg som tar grunnskolelærarutdanning 5-10', 2),
 ('Dersom du fullfører grunnskolelærarutdanning trinn 5-10, og jobbar som lærar i minst tre år, kan du få sletta 51 000 kroner av studielånet ditt. Vilkåra er at du fullfører studia på normert tid og at du har jobba som lærar i minst tre av dei første seks åra etter du har fullført utdanninga.',
  2),
 ('For deg som tar lektorutdanning for trinn 8-13', 2),
 ('Dersom du fullfører lektorutdanning trinn 8-13, og jobbar som lærar i minst tre år, kan du få sletta 51 000 kroner av studielånet ditt. Vilkåra er at du fullfører studia på normert tid og at du har jobba som lærar i minst tre av dei første seks åra etter du har fullført utdanninga.',
  2),
 ('For deg som er lærar i Nord-Noreg', 2),

In [ ]:
duplicates = set()
for text, count in Counter(nynorsk_sentences).most_common():
    if count < 2:
        break
    duplicates.add(text)

In [ ]:
len(duplicates)

405

### Hvis duplikatsetningene forekommer i samme dokument er det greit

In [ ]:
dupe_indices = [i for i, sent in enumerate(nynorsk_sentences) if sent in duplicates]
len(dupe_indices)

2331

In [ ]:
len(set(dupe_indices))

2331

In [ ]:
G.remove_nodes_from([node for pair in pairs for node in pair])

In [ ]:
nn, _  = zip(*doc_edges)

In [ ]:
len(set(nn)), len(nynorske)

(251, 256)

In [ ]:
G.number_of_nodes()

319

In [ ]:
nb_bm_cut_off = len(nynorsk_sent_to_doc_indexer)
nb_bm_cut_off

5958

In [ ]:
print(pairs[0])

{42, 266}

In [ ]:
len(nynorsk_embeddings)

5958